apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-cm
  namespace: prod-env
data:
  componentVersion: '{"commitTitle":"${CI_COMMIT_TITLE}","lastCommit":"${CI_COMMIT_SHORT_SHA}","release":"${CI_COMMIT_TAG}"}'
  dbUser: rw__COMPONENT_NAME_
  dbPassword: "${PROD_dbPassword}"
  dbHost: "mongodb+srv://prod-pri.glxjo.gcp.mongodb.net/test?retryWrites=true&w=majority"
  dbName: "_COMPONENT_NAME_"
  kafkaUrl: "prod-ultraio-kafka-production.aivencloud.com:21811"
  schemaRegistryUrl: "http://kafka-schema-registry-svc:8081"
  useKafkaWithSSL: "true"
  jwtSecretKey: ultraSecretKey
  jwtEncryptionKey: ultraEncryptionKey
  mongooseDebug: "false"
  consoleLogLevel: "info"
  logFormat: "json"
  runningEnvironment: "prod-env"
  performanceLogEnabled: "false"
