apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-cm
  namespace: test-env
data:
  componentVersion: '{"commitTitle":"${CI_COMMIT_TITLE}","lastCommit":"${CI_COMMIT_SHORT_SHA}","release":"${CI_COMMIT_TAG}"}'
  dbUser: rw__COMPONENT_NAME_
  dbPassword: "${TEST_dbPassword}"
  dbHost: "mongodb+srv://test-pri.0jrxy.gcp.mongodb.net/test?retryWrites=true&w=majority"
  dbName: "_COMPONENT_NAME_"
  kafkaUrl: "dev-ultraio-kafka-dev.aivencloud.com:21811"
  schemaRegistryUrl: "http://kafka-schema-registry-svc:8081"
  useKafkaWithSSL: "true"
  jwtSecretKey: ultraSecretKey
  jwtEncryptionKey: ultraEncryptionKey
  mongooseDebug: "false"
  consoleLogLevel: "silly"
  logFormat: "json"
  runningEnvironment: "test-env"
  performanceLogEnabled: "true"
